/*
 * @autor_name Ennio Sousa
 * @autor_site http://uid.me/shzlot
 *
 * Copyright (c) 2015 Ennio.
 * All rights reserved. This program and the accompanying materials
 */
package View;

import Controller.Administrador;

/**
 *
 * @author Ennio
 */
public class AdminEditarUsuario extends javax.swing.JFrame {

    Administrador administrador = new Administrador();
    String codUsuario = null;

    /**
     * Creates new form EditarUsuario
     */
    private AdminEditarUsuario() {
        initComponents();

    }

    public AdminEditarUsuario(String codUsuario) {
        initComponents();
        this.codUsuario = codUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarUsuarios = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        labelEditUsuarioCodUsuario = new javax.swing.JLabel();
        labelEditUsuarioNome = new javax.swing.JLabel();
        labelEditUsuarioCpf = new javax.swing.JLabel();
        labelEditUsuarioEmail = new javax.swing.JLabel();
        campoEditUsuarioCodUsuario = new javax.swing.JTextField();
        campoEditUsuarioNome = new javax.swing.JTextField();
        campoEditUsuarioCpf = new javax.swing.JTextField();
        campoEditUsuarioEmail = new javax.swing.JTextField();
        labelEditUsuarioSenha = new javax.swing.JLabel();
        labelEditUsuarioTelefone = new javax.swing.JLabel();
        labelEditUsuarioTipoUsuario = new javax.swing.JLabel();
        labelEditUsuariocodGrupoUsuario = new javax.swing.JLabel();
        campoEditUsuarioSenha = new javax.swing.JTextField();
        campoEditUsuarioTelefone = new javax.swing.JTextField();
        campoEditUsuarioCodGrupo = new javax.swing.JTextField();
        btnSalvarEditUsuario = new javax.swing.JButton();
        campoEditUsuarioTipoUsuario = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar o usuário");
        setPreferredSize(new java.awt.Dimension(700, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnListarUsuarios.setText("Voltar para a lista de usuarios");
        btnListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuariosActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar informações do usuário"));

        labelEditUsuarioCodUsuario.setText("Cód. do usuário");

        labelEditUsuarioNome.setText("Nome completo");

        labelEditUsuarioCpf.setText("CPF");

        labelEditUsuarioEmail.setText("Email");

        campoEditUsuarioCodUsuario.setEditable(false);

        labelEditUsuarioSenha.setText("Senha");

        labelEditUsuarioTelefone.setText("Telefone");

        labelEditUsuarioTipoUsuario.setText("Tipo usuário");

        labelEditUsuariocodGrupoUsuario.setText("Cód. do grupo");

        campoEditUsuarioCodGrupo.setEnabled(false);

        btnSalvarEditUsuario.setText("Salvar as informações");
        btnSalvarEditUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditUsuarioActionPerformed(evt);
            }
        });

        campoEditUsuarioTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inscrito", "Administrador" }));
        campoEditUsuarioTipoUsuario.setSelectedIndex(1);
        campoEditUsuarioTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEditUsuarioTipoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvarEditUsuario)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labelEditUsuarioCodUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(campoEditUsuarioCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelEditUsuarioCpf)
                                            .addComponent(labelEditUsuarioNome))
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(labelEditUsuarioEmail)
                                        .addGap(73, 73, 73)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoEditUsuarioEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(campoEditUsuarioCpf)
                                    .addComponent(campoEditUsuarioNome))
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEditUsuariocodGrupoUsuario)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEditUsuarioTelefone)
                                    .addComponent(labelEditUsuarioSenha)
                                    .addComponent(labelEditUsuarioTipoUsuario))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoEditUsuarioCodGrupo)
                            .addComponent(campoEditUsuarioTelefone)
                            .addComponent(campoEditUsuarioSenha)
                            .addComponent(campoEditUsuarioTipoUsuario, 0, 200, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEditUsuarioCodUsuario)
                    .addComponent(campoEditUsuarioCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEditUsuarioSenha)
                    .addComponent(campoEditUsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEditUsuarioNome)
                    .addComponent(campoEditUsuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEditUsuarioTelefone)
                    .addComponent(campoEditUsuarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEditUsuarioCpf)
                    .addComponent(campoEditUsuarioCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEditUsuarioTipoUsuario)
                    .addComponent(campoEditUsuarioTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEditUsuarioEmail)
                    .addComponent(campoEditUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEditUsuariocodGrupoUsuario)
                    .addComponent(campoEditUsuarioCodGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSalvarEditUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarUsuarios)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListarUsuarios)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuariosActionPerformed
        // TODO add your handling code here:
        AdminListarUsuarios lu = new AdminListarUsuarios();
        lu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarUsuariosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // quando a janela abre
        //campoEditUsuarioCodUsuario.setText(codUsuario);

        /*
         índice[0] --> cod_usuario
         índice[1] --> cpf
         índice[2] --> nome
         índice[3] --> email
         índice[4] --> telefone
         índice[5] --> senha
         índice[6] --> cod_grupo
         índice[7] --> tipo_usuario
         */
        String[] dadosUsuario = administrador.getDadosUsuario(this.codUsuario);
        campoEditUsuarioCodUsuario.setText(dadosUsuario[0]);
        campoEditUsuarioCpf.setText(dadosUsuario[1]);
        campoEditUsuarioNome.setText(dadosUsuario[2]);
        campoEditUsuarioEmail.setText(dadosUsuario[3]);
        campoEditUsuarioTelefone.setText(dadosUsuario[4]);
        campoEditUsuarioSenha.setText(dadosUsuario[5]);
        campoEditUsuarioCodGrupo.setText(dadosUsuario[6]);

        /*
         indices da caixa de seleção
         * 0 - Inscrito
         * 1 - administrador
        
         tipos de usuarios
         * A ou a - Administradores
         * I ou i - Inscritos
         */
        int a = (dadosUsuario[7].equals("a" + "") || dadosUsuario[7].equals("A" + "")) ? 1 : 0;
        campoEditUsuarioTipoUsuario.setSelectedIndex(a);
    }//GEN-LAST:event_formWindowOpened

    private void campoEditUsuarioTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEditUsuarioTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditUsuarioTipoUsuarioActionPerformed

    private void btnSalvarEditUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditUsuarioActionPerformed
        // TODO add your handling code here:
        String cod_usuario = campoEditUsuarioCodUsuario.getText();
        String cpf = campoEditUsuarioCpf.getText();
        String nome = campoEditUsuarioNome.getText();
        String email = campoEditUsuarioEmail.getText();
        String telefone = campoEditUsuarioTelefone.getText();
        String senha = campoEditUsuarioSenha.getText();
        String cod_grupo = campoEditUsuarioCodGrupo.getText();
        String tipo_usuario = String.valueOf(campoEditUsuarioTipoUsuario.getSelectedItem());
        char tipo_usuario2 = (tipo_usuario.equals("" + "Administrador")) ? 'a' : 'i';
        administrador.setDadosUsuario(cod_usuario, cpf, nome, email, telefone, senha, cod_grupo, tipo_usuario2);
    }//GEN-LAST:event_btnSalvarEditUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarUsuarios;
    private javax.swing.JButton btnSalvarEditUsuario;
    private javax.swing.JTextField campoEditUsuarioCodGrupo;
    private javax.swing.JTextField campoEditUsuarioCodUsuario;
    private javax.swing.JTextField campoEditUsuarioCpf;
    private javax.swing.JTextField campoEditUsuarioEmail;
    private javax.swing.JTextField campoEditUsuarioNome;
    private javax.swing.JTextField campoEditUsuarioSenha;
    private javax.swing.JTextField campoEditUsuarioTelefone;
    private javax.swing.JComboBox campoEditUsuarioTipoUsuario;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelEditUsuarioCodUsuario;
    private javax.swing.JLabel labelEditUsuarioCpf;
    private javax.swing.JLabel labelEditUsuarioEmail;
    private javax.swing.JLabel labelEditUsuarioNome;
    private javax.swing.JLabel labelEditUsuarioSenha;
    private javax.swing.JLabel labelEditUsuarioTelefone;
    private javax.swing.JLabel labelEditUsuarioTipoUsuario;
    private javax.swing.JLabel labelEditUsuariocodGrupoUsuario;
    // End of variables declaration//GEN-END:variables
}
