/*
 * @autor_name Ennio Sousa
 * @autor_site http://uid.me/shzlot
 *
 * Copyright (c) 2015 Ennio.
 * All rights reserved. This program and the accompanying materials
 */
package View;

/**
 *
 * @author Ennio
 */
public class AdminPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public AdminPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTopo = new javax.swing.JMenuBar();
        menuMeusDados = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenu();
        menuNovoUsuario = new javax.swing.JMenuItem();
        menuListaUsuarios = new javax.swing.JMenuItem();
        menuEvento = new javax.swing.JMenu();
        menuNovoEvento = new javax.swing.JMenuItem();
        menuListaEventos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMeusDados.setText("Meus dados");
        menuTopo.add(menuMeusDados);

        menuUsuarios.setText("Usuários");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });

        menuNovoUsuario.setText("Novo usuário");
        menuNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuNovoUsuario);

        menuListaUsuarios.setText("Lista de usuários");
        menuListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuListaUsuarios);

        menuTopo.add(menuUsuarios);

        menuEvento.setText("Eventos");

        menuNovoEvento.setText("Novo evento");
        menuEvento.add(menuNovoEvento);

        menuListaEventos.setText("Lista de eventos");
        menuEvento.add(menuListaEventos);

        menuTopo.add(menuEvento);

        setJMenuBar(menuTopo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoUsuarioActionPerformed
        // TODO add your handling code here:
        Cadastro c = new Cadastro();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNovoUsuarioActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaUsuariosActionPerformed
        // TODO add your handling code here:
        AdminListarUsuarios alu = new AdminListarUsuarios();
        alu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuListaUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuEvento;
    private javax.swing.JMenuItem menuListaEventos;
    private javax.swing.JMenuItem menuListaUsuarios;
    private javax.swing.JMenu menuMeusDados;
    private javax.swing.JMenuItem menuNovoEvento;
    private javax.swing.JMenuItem menuNovoUsuario;
    private javax.swing.JMenuBar menuTopo;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
